# Generated by Django 4.0.3 on 2022-04-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptoms',
            old_name='name',
            new_name='Name',
        ),
    ]
