# Generated by Django 3.2.4 on 2022-04-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_symptomsnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases_Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=50)),
                ('Symptom', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='symptoms',
        ),
        migrations.DeleteModel(
            name='SymptomsNew',
        ),
    ]
